service:
  extensions: [jaeger_storage, jaeger_query]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger_storage_exporter]

extensions:
  jaeger_query:
    base_path: /ui
    storage:
      traces: trace_storage
  jaeger_storage:
    backends:
      trace_storage:
        badger:
          directories:
            keys: "/tmp/jaeger"
            values: "/tmp/jaeger"
          ephemeral: false
          ttl:
            spans: 48h
      trace_archive_storage:
        badger:
          directories:
            keys: "/tmp/jaeger_archive"
            values: "/tmp/jaeger_archive"
          ephemeral: false
          ttl:
            spans: 720h
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
exporters:
  jaeger_storage_exporter:
    trace_storage: trace_storage
